package org.krulvis.lr.sentiment

object SentimentAnalysis {
    //(empirically derived mean sentiment intensity rating increase for booster words)
    const val B_INCR = 0.293
    const val B_DECR = -0.293

    //(empirically derived mean sentiment intensity rating increase for using
    //ALLCAPs to emphasize a word)
    const val C_INCR = 0.733

    const val N_SCALAR = -0.74

    val NEGATE = arrayOf(
        "aint",
        "arent",
        "cannot",
        "cant",
        "couldnt",
        "darent",
        "didnt",
        "doesnt",
        "ain't",
        "aren't",
        "can't",
        "couldn't",
        "daren't",
        "didn't",
        "doesn't",
        "dont",
        "hadnt",
        "hasnt",
        "havent",
        "isnt",
        "mightnt",
        "mustnt",
        "neither",
        "don't",
        "hadn't",
        "hasn't",
        "haven't",
        "isn't",
        "mightn't",
        "mustn't",
        "neednt",
        "needn't",
        "never",
        "none",
        "nope",
        "nor",
        "not",
        "nothing",
        "nowhere",
        "oughtnt",
        "shant",
        "shouldnt",
        "uhuh",
        "wasnt",
        "werent",
        "oughtn't",
        "shan't",
        "shouldn't",
        "uh-uh",
        "wasn't",
        "weren't",
        "without",
        "wont",
        "wouldnt",
        "won't",
        "wouldn't",
        "rarely",
        "seldom",
        "despite",
    )

//    booster/dampener 'intensifiers' or 'degree adverbs'
//    https://en.wiktionary.org/wiki/Category:English_degree_adverbs

    val BOOSTER_MAP = arrayOf(
        "absolutely" to B_INCR,
        "amazingly" to B_INCR,
        "awfully" to B_INCR,
        "completely" to B_INCR,
        "considerably" to B_INCR,
        "decidedly" to B_INCR,
        "deeply" to B_INCR,
        "effing" to B_INCR,
        "enormously" to B_INCR,
        "entirely" to B_INCR,
        "especially" to B_INCR,
        "exceptionally" to B_INCR,
        "extremely" to B_INCR,
        "fabulously" to B_INCR,
        "flipping" to B_INCR,
        "flippin" to B_INCR,
        "fricking" to B_INCR,
        "frickin" to B_INCR,
        "frigging" to B_INCR,
        "friggin" to B_INCR,
        "fully" to B_INCR,
        "fucking" to B_INCR,
        "greatly" to B_INCR,
        "hella" to B_INCR,
        "highly" to B_INCR,
        "hugely" to B_INCR,
        "incredibly" to B_INCR,
        "intensely" to B_INCR,
        "majorly" to B_INCR,
        "more" to B_INCR,
        "most" to B_INCR,
        "particularly" to B_INCR,
        "purely" to B_INCR,
        "quite" to B_INCR,
        "really" to B_INCR,
        "remarkably" to B_INCR,
        "so" to B_INCR,
        "substantially" to B_INCR,
        "thoroughly" to B_INCR,
        "totally" to B_INCR,
        "tremendously" to B_INCR,
        "uber" to B_INCR,
        "unbelievably" to B_INCR,
        "unusually" to B_INCR,
        "utterly" to B_INCR,
        "very" to B_INCR,
        "almost" to B_DECR,
        "barely" to B_DECR,
        "hardly" to B_DECR,
        "just enough" to B_DECR,
        "kind of" to B_DECR,
        "kinda" to B_DECR,
        "kindof" to B_DECR,
        "kind-of" to B_DECR,
        "less" to B_DECR,
        "little" to B_DECR,
        "marginally" to B_DECR,
        "occasionally" to B_DECR,
        "partly" to B_DECR,
        "scarcely" to B_DECR,
        "slightly" to B_DECR,
        "somewhat" to B_DECR,
        "sort of" to B_DECR,
        "sorta" to B_DECR,
        "sortof" to B_DECR,
        "sort-of" to B_DECR,
    )

    //# check for special case idioms using a sentiment-laden keyword known to SAGE
    val SPECIAL_CASE_IDIOMS = arrayOf(
        "the shit" to 3,
        "the bomb" to 3,
        "bad ass" to 1.5,
        "yeah right" to -2,
        "cut the mustard" to 2,
        "kiss of death" to -1.5,
        "hand to mouth" to -2,
    )

    val REGEX_REMOVE_PUNCTUATION = Regex("[^\\w\\s]")
}
